services:
  - type: web
    name: fraud-detection-ml
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: cd app && streamlit run app.py --server.port $PORT --server.address 0.0.0.0
    plan: free